expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
exposecontroller:
  config:
    domain: 104.211.1.206.nip.io
    exposer: Ingress
    http: "true"
    tlsacme: ""
    pathmode: ""
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  servers:
    gitea: []
    ghe: []
    global:
      envvars:
        DOCKER_REGISTRY: pcjenkinsx19.azurecr.io
        TILLER_NAMESPACE: kube-system
  enabled: null
prow:
  user: ""
  hmactoken: ""
  oauthtoken: ""
pipelinesecrets:
  dockerconfig: '{"auths":{"pcjenkinsx19.azurecr.io":{"auth":"cGNqZW5raW5zeDE5Om85cm4wMWl2M2JsOFpJRS9xT3dWSDF6ZDFBdnZiZUZY"}}}'
controllerbuild:
  enabled: null
